#!/bin/bash -eu

# usage:
#     setup-tsenv [<directory>]

# determine target dir by arg or current dir
TARGET_DIR=$(pwd)
if [ ${#} -eq 1 ]; then
  TARGET_DIR=${1}
fi

# move to directory
mkdir -p ${TARGET_DIR}
cd ${TARGET_DIR}

# setup Node environment
cat << EOT >> package.json
{
  "name": "hello",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "build": "gulp build",
    "main": "node main.js",
    "watch": "gulp watch"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-typescript": "^3.1.2",
    "typescript": "^2.0.6"
  }
}
EOT

npm install

# setup TypeScript environment
cat << EOT >> tsconfig.json
{
    "files": ["main.ts"],
    "filesGlob": ["*.ts"],
    "compilerOptions": {
        "noImplicitAny": true,
        "target": "es6"
    }
}
EOT

# create blank source
cat << EOT >> main.ts
console.log("Hello world!");
EOT


# gulp
cat << EOT >> gulpfile.js
var gulp = require('gulp');
var typescript = require('gulp-typescript');

gulp.task('build', function() {
  var options = {out: 'main.js'};
  gulp.src([
    './*.ts',
    '!./node_modules/**'
  ])
  .pipe(typescript(options))
  .pipe(gulp.dest('./'));
});

gulp.task('watch', function(){
  gulp.watch('./*.js', ['build']);
});
EOT
