#!/bin/bash -eu

# usage:
#     setup-tsenv [<directory>]

# determine target dir by arg or current dir
TARGET_DIR=$(pwd)
if [ ${#} -eq 1 ]; then
  TARGET_DIR=${1}
fi

# move to directory
mkdir -p ${TARGET_DIR}
cd ${TARGET_DIR}

# setup Node environment
npm init -y
npm install --save-dev typescript
#npm install --save-dev gulp gulp-typescript

# setup TypeScript environment
cat << EOT >> tsconfig.json
{
    "files": ["index.ts"],
    "filesGlob": ["*.ts"],
    "compilerOptions": {
        "noImplicitAny": true,
        "target": "es6"
    }
}
EOT

# create blank source
cat << EOT >> index.ts
console.log("Hello world!");
EOT
