#!/bin/bash -eu

# usage:
#     setup-tsenv [<directory>]

# determine target dir by arg or current dir
TARGET_DIR=$(pwd)
if [ ${#} -eq 1 ]; then
  TARGET_DIR=${1}
fi

# move to directory
cd ${TARGET_DIR}

# setup Node environment
npm install --save-dev typescript gulp gulp-typescript

# setup TypeScript environment
